prompt_template="You are an Automated Chat System :\nThe task is to give a consistent and engaging response to what the User says based  on the summary of the dialog exchange between you and the User. Learn from the example below.\nExample:\nThis is a summary of a dialog exchange between you and the User:\n{0}\nBased on the summary of the dialog exchange, give a consistent and engaging response to the following dialogue by the User.\nUser:{1} \nBot:{2}\nNow try it yourself.\nThis is a summary of a dialog exchange between you and the User:\n{3}\nGiven the summary of the dialog exchange between User and Bot, give a consistent and engaging response  to the following dialog by User\nUser:{4}\n Bot:"
shorter_prompt_template="You are an Automated Chat System :\nThis is a summary of a dialog exchange between User and Bot:\n{0}\nGiven the summary of the dialog exchange between User and Bot, give a consistent and engaging response to the following dialog by User.\nUser:{1}\n Bot:"


current_utterance_short_template="Give a consistent and engaging response to the following dialog spoken by User\nUser:{0}\n Bot:"
current_utterance_template="Give a consistent and engaging response to the following dialog spoken by User.Learn from the example first.\nUser: {0}\n Bot: {1}\nNow try it yourself:\nGive a consistent and engaging response  to the following dialog spoken by User\nUser:{2}\n Bot:"

prompt_template_persona="You are an Automated Chat System :\nLearn from the below example on how to use background details to generate a consistent and engaging response to what User says.\nExample:\nHere are some background details about User:\n{1}\nHere are some background details about Bot:\n{0}\nGiven the background details of  User and Bot, give a consistent and engaging response to the following dialog spoken by User.\nUser: {2}\n Bot: {3}\nNow try it yourself:\nHere are some background details about User:\n{4}\nHere are some background details about Bot:\n{5}\nGiven the background details of  User and Bot , give a consistent and engaging response to the following dialog spoken by User\nUser: {6}\nBot:"

shorter_prompt_template_persona="You are an Automated Chat System :\nHere are some background details about User:\n{0}\nHere are some background details about Bot:\n{1}\nGiven the background details of  User and Bot , give a consistent and engaging response to the following dialog spoken by User\nUser: {2}\nBot:"

prompt_template_persona_and_summary="You are an Automated Chat System :\nLearn from the below example on how to generate consistent and engaging responses between User and Bot given background details along with summary.\nExample:\nHere are some background details about User:\n{1}\nHere are some background details about Bot:\n{0}\nThis is a summary of a dialog exchange between User and Bot:\n{2}\nGiven the background details and the summary of the dialog exchange between User and Bot, give a consistent and engaging response to the following dialog by User.\nUser:{3}\n Bot:{4}\nNow try it yourself:\nHere are some background details about User:\n{5}\nHere are some background details about Bot:\n{6}\nThis is a summary of a dialog exchange between User and Bot:\n{7}\nGiven the summary of the dialog exchange between User and Bot and their background details, give a consistent and engaging response  to the following dialog spoken by User\nUser:{8}"
shorter_prompt_template_persona_and_summary="You are an Automated Chat System :\nHere are some background details about User:\n{0}\nHere are some background details about Bot:\n{1}\nThis is a summary of a dialog exchange between User and Bot:\n{2}\nGiven the background details and the summary of the dialog exchange between User and Bot, give a consistent and engaging response  to the following dialog by User\nUser:{3}"

shorter_prompt_template_onlyknowledge="You are an Automated Chat System :\nHere is some data on the topics User and Bot are discussing about:\n{0}\nBased on the information about the topics being discussed by User and Bot , give a consistent and engaging response to the following dialog spoken by User\nUser: {1}\nBot:"
prompt_template_onlyknowledge="You are an Automated Chat System :\nLearn from the below example on how to use information about the topics being discussed by User and Bot to generate a suitable response by Bot on what User says. \nExample:\nHere is some infomation about the topics User and Bot are discussing about:\n{0}\nBased on the above information, give a suitable response to the following dialog spoken by User.\nUser:{1} Bot:\n{2}\nNow try it yourself:\nHere is some information about the topics being discussed by User and Bot:\n{3}\nGiven the information about the topics being discussed by User and Bot , give a consistent and engaging response to the following dialog spoken by User\nUser: {4}\nBot:"

shorter_prompt_template_knowledge_and_summary="You are an Automated Chat System :\nHere is some data on the topics User and Bot are discussing about:\n{0}\nHere is a summary of the conversation between User and Bot:\n{1}\nBased on the conversation summary and the information about the topics being discussed by User and Bot , give a consistent and engaging response to the following dialog spoken by User\nUser: {2}\nBot:"
prompt_template_knowledge_and_summary="You are an Automated Chat System :\nLearn from the below example on how to use the conversation summary along with the information about the topics being discussed by User and Bot to generate a suitable response by Bot on what User says. \nExample:\nHere is some infomation about the topics User and Bot are discussing about:\n{0}\nHere is the conversation summary between User and Bot:\n{1}\nBased on the above information, give a suitable response to the following dialog spoken by User.\nUser:{2} Bot:\n{3}\nNow try it yourself:\nHere is some information about the topics being discussed by User and Bot:\n{4}\nHere is a summary of the conversation between User and Bot:\n{5}\nGiven the conversation summary and the information about the topics being discussed by User and Bot , give a consistent and engaging response to the following dialog spoken by User\nUser: {6}\nBot:"

fsb_prompt="User Information:\n{0}\nBot information:\n{1}\nDialogue:User: {2}\nBot: {3}\nUser: {4}\nBot:"
#All for multi session chat
ppl_based_cutt_T0='predict what is the next thing that the Bot might say after hearing this dialogue by User?\\nUser: "{0}"'
ppl_based_cutt_T0_ex='Predict what might have been said by the Bot following this dialogue by the User. Learn from the example first.\\nUser: "{0}"\\nBot: "{1}"\\nNow try it yourself. Predict what might have been said by the Bot following this dialogue by the User.\\nUser: "{2}"'
ppl_based_cutt_flanT5='how would the Bot respond to the dialogues initiated by the User in a way that the conversation continues to be consistent and interesting.\\nUser: "{0}"'
ppl_based_cutt_flanT5_ex='Predict what is the next thing that the Bot might say after hearing this dialogue by User? Learn from the example first.\\nUser: "{0}"\\nBot: "{1}"\\nNow try it yourself. Predict what is the next thing that the Bot might say after hearing this dialogue by User?\\nUser: "{2}"'

ppl_based_cutt_tk_instruct='predict what the Bot would say after listening to the User\'s dialogue.\\nUser: "{0}"'
ppl_based_cutt_tk_instruct_ex='Predict what might have been said by the Bot following this dialogue by the User. Learn from the example first.\\nUser: "{0}"\\nBot: "{1}"\\nNow try it yourself. Predict what might have been said by the Bot following this dialogue by the User.\\nUser: "{2}"'
pegasusft_template_pplbased_T0='Here is a summary of the conversation between User and Bot:\n"{0}"\nBased on the summary of conversation between User and Bot, what do you think Bot will say next?\nUser: "{1}"'
pegasusft_template_pplbased_flanT5='Here is a summary of the conversation between User and Bot:\n"{0}"\nBased on the dialogue between the User and the Bot so far, try to anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{1}"'
pegasusft_template_pplbased_tk_instruct='Here is a summary of the conversation between User and Bot:\n"{0}"\nBased on the given summary of the conversation between the User and the Bot, predict what Bot would say after the User said this dialogue.\nUser: "{1}"'
pegasusft_template_pplbased_flanT5_withex='The task is to predict what the Bot will say next, Given the summary of conversation between User and Bot. Take a look at the following example for guidance.\n Example:\n Here is a conversation summary between User and Bot: \n "{0}" \n Based on the summary of the conversation given, what do you think the Bot will say next? \n User: "{1}" \n Bot: "{2}" \n Now try it yourself. \n Here is a conversation summary between User and Bot: \n "{3}" \n Based on the summary of conversation between User and Bot, what do you think Bot will say next? \n User: "{4}"'
pegasusft_template_pplbased_tk_instruct_withex='The task is to predict what might have been said in response to the User\'s dialogue in the light of the provided conversation summary. Learn from the example first.\n Example:\n Here is a conversation summary between User and Bot: \n"{0}"\n In the light of this given summary predict might have been said in response to the following dialogue by the User.\n User: "{1}"\n Bot: "{2}"\n Now try it yourself.\n Here is a conversation summary between User and Bot:\n"{3}"\n In the light of the provided conversation summary between the User and the Bot, predict what might have been said following this dialogue by the User.\n User: "{4}"'
pegasusft_template_pplbased_T0_withex='The task is to predict a suitable response to the User\'s dialogue based on the given conversation summary. Take a look at the following example for guidance.\n Example:\n Here is a conversation summary between User and Bot:\n"{0}"\nBased on the conversation between the User and the Bot, predict what the Bot might have said in response to the User\'s dialogue.\nUser: "{1}"\nBot: "{2}"\nNow try it yourself.\nHere is a conversation summary between User and Bot:\n"{3}"\nBased on the conversation between the User and the Bot, predict what the Bot might have said in response to the User\'s dialogue.\nUser: "{4}"'
only_persona_pplbased_T0='Here are some persona details about the User and Bot:\n"{0}"\n"{1}"\nBased on the given persona details about the User and the Bot, predict what Bot would say after the User said this dialogue.\nUser: "{2}"'
only_persona_pplbased_T0_withex='The task is to give a suitable response to the User based on the information given about the User and the Bot. Learn from the example first.\nExample:\n Here is some information about the User and Bot:\n"{0}"\n"{1}"\nBased on the information provided about the User and the Bot, predict what the Bot might have said in response to the User\'s dialogue.\nUser: "{2}"\nBot: "{3}"\nNow try it yourself.\nHere is some information about the User and Bot:\n"{4}"\n"{5}\nBased on the information provided about the User and the Bot, predict what the Bot might have said in response to the User\'s dialogue.\nUser: "{6}"'
only_persona_pplbased_flanT5='Here is some information about the User and Bot:\n"{0}"\n"{1}"\nBased on the information provided about the User and the Bot, predict what the Bot might have said in response to the User\'s dialogue.\nUser: "{2}"'
only_persona_pplbased_flanT5_withex='The task is to give a suitable response to what the User says, based on the information given about the User and the Bot. Learn from the example first.\nExample:\nHere is some information about the User and Bot:\n"{0}"\n"{1}"\n Based on the information provided about the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{2}"\nBot: "{3}"\nNow try it yourself.\nHere is some information about the User and Bot:\n"{4}"\n"{5}\nBased on the information provided about the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{6}"'

persona_and_summary_pplbased_T0='Here are some persona details about the User and Bot:\n"{0}"\n"{1}"\nHere is a conversation summary between User and Bot:\n"{2}"\nBased on the persona information of the User and the Bot and their conversation summary so far, anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{3}"'
persona_and_summary_pplbased_T0_withex='The task is to give a suitable response to what the User says based on the personal details of the User and the Bot and their conversation summary. Learn from the example first.\nExample:\nHere is some information about User and Bot:\n"{0}"\n"{1}"\nHere is a conversation summary between User and Bot:\n"{2}"\n Based on the persona information of the User and the Bot and their conversation summary so far, anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{3}"\nBot: "{4}"\nNow try it yourself.\nHere are some persona details about the User and Bot:\n"{5}"\n"{6}\nHere is a conversation summary between User and Bot.\n"{7}"\nBased on the persona information of the User and the Bot and their conversation summary so far, anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{8}"'
persona_and_summary_pplbased_flanT5_withex='The task is to give a suitable response to what the User says based on the personal details of the User and the Bot and their conversation summary. Take a look at the example for guidance.\nExample:\nHere is some information about User and Bot:\n"{0}"\n"{1}"\nHere is a conversation summary between User and Bot:\n"{2}"\nIn the light of the conversation summary and the information provided about the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{3}"\nBot: "{4}"\nNow try it yourself.\nHere is some information about the User and Bot:\n"{5}"\n"{6}\nHere is a conversation summary between User and Bot.\n"{7}"\nIn the light of the conversation summary and the information provided about the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{8}"'
persona_and_summary_pplbased_flanT5='Here are some persona details about the User and Bot:\n"{0}"\n"{1}"\nHere is a conversation summary between User and Bot:\n"{2}"\nBased on the persona information of the User and the Bot and their conversation summary so far, anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{3}"'

semantic_template_pplbased_T0=pegasusft_template_pplbased_T0
semantic_template_pplbased_flanT5=pegasusft_template_pplbased_flanT5
semantic_template_pplbased_tk_instruct='Here is a summary of the conversation between User and Bot:\n"{0}"\nBased on the given summary of the conversation between the User and the Bot, predict what Bot would say after the User said this dialogue.\nUser: "{1}"'
prevutt_template_pplbased_T0_withex='The task is to give a suitable response to what the User says based on the given conversation history between User and Bot. Take a look at the following example for guidance.\nHere is a conversation summary between User and Bot:\n"{0}"\nBased on the dialogue between the User and the Bot so far, try to anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{1}"\nBot: "{2}"\nNow try it yourself.\nHere is a conversation summary between User and Bot:\n"{3}"\nBased on the dialogue between the User and the Bot so far, try to anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{4}"'
semantic_template_pplbased_flanT5_withex=pegasusft_template_pplbased_flanT5_withex
semantic_template_pplbased_T0_withex='The task is to give a suitable response to what the User says based on the given conversation history between User and Bot. Take a look at the following example for guidance.\nHere is a conversation summary between User and Bot:\n"{0}"\nBased on the dialogue between the User and the Bot so far, try to anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{1}"\nBot: "{2}"\nNow try it yourself.\nHere is a conversation summary between User and Bot:\n"{3}"\nBased on the dialogue between the User and the Bot so far, try to anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{4}"'

dialogcse_template_pplbased_flanT5_withex='Here is a conversation summary between User and Bot:\n"{0}"\nBased on the summary of conversation between User and Bot, what do you think Bot will say next? Take a look at the following example for guidance.\nExample:\nUser: "{1}"\nBot: "{2}"\nNow try it yourself.\nHere is a conversation summary between User and Bot:\n"{3}"\nBased on the summary of conversation between User and Bot, what do you think Bot will say next?\nUser: "{4}"'
dialogcse_template_pplbased_T0_withex='Here is a conversation summary between User and Bot:\n"{0}"\nBased on the dialogue between the User and the Bot so far, try to anticipate what the Bot\'s response might be to the User\'s next statement. Learn from the example first.\nExample:\nUser: "{1}"\nBot: "{2}"\nNow try it yourself.\nHere is a conversation summary between User and Bot:\n"{3}"\nBased on the dialogue between the User and the Bot so far, try to anticipate what the Bot\'s response might be to the User\'s next statement.\nUser: "{4}"'
dialogcse_template_pplbased_flanT5='Here is a summary of the conversation between User and Bot:\n"{0}"\nBased on the summary of conversation between User and Bot, what do you think Bot will say next?\nUser: "{1}"'
dialogcse_template_pplbased_T0='Here is a summary of the conversation between User and Bot:\n"{0}"\nBased on the summary of conversation between User and Bot, what do you think Bot will say next?\nUser: "{1}"'

only_knowledge_pplbased_T0='Here is some data on the topics the User and Bot are discussing about:\n"{0}"\nIn the light of the information about the topics being discussed by the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{1}"'
only_knowledge_pplbased_flanT5='Here is some data on the topics the User and Bot are discussing about:\n"{0}"\nBased on the data about the topics being discussed by the User and the Bot, anticipate what the Bot might have said next in response to the User\'s dialogue.\nUser: "{1}"'
 
only_knowledge_pplbased_T0_withex='The task is to give a suitable response to what the User says based on the information about the topics the User and Bot are discussing about. Learn from the example first.\nExample:\nHere is some information on the topics being discussed by User and Bot:\n"{0}"\nIn the light of the information about the topics being discussed by the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{1}"\nBot: "{2}"\nNow try it yourself.\nHere is some data on the topics the User and Bot are discussing about:\n"{3}"\nIn the light of the information about the topics being discussed by the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{4}"'
only_knowledge_pplbased_flanT5_withex='The task is to give a suitable response to what the User says based on the information about the topics the User and Bot are discussing about. Learn from the example first.\nExample:\nHere is some information on the topics being discussed by User and Bot:\n"{0}"\nBased on the data about the topics being discussed by the User and the Bot, anticipate what the Bot might have said next in response to the User\'s dialogue.\nUser: "{1}"\nBot: "{2}"\nNow try it yourself.\nHere is some data on the topics the User and Bot are discussing about:\n"{3}"\nBased on the data about the topics being discussed by the User and the Bot, anticipate what the Bot might have said next in response to the User\'s dialogue.\nUser: "{4}"'
    

knowledge_and_summary_pplbased_T0='Here is some data on the topics the User and Bot are discussing about:\n"{0}"\nHere is a conversation summary between User and Bot:\n"{1}"\nIn the light of the chat history and information about topics that the User and the Bot are chatting on, predict what might have been said following this dialogue by the User.\nUser: "{2}"'
knowledge_and_summary_pplbased_flanT5='Here is some information on the topics being discussed by User and Bot:\n"{0}"\nHere is a conversation summary between User and Bot:\n"{1}"\nIn the light of the conversation history and information about the topics being discussed by the User and the Bot, predict what might have been said following this dialogue by the User.\nUser: "{2}"'
knowledge_and_summary_pplbased_T0_withex='The task is to give a suitable response to what the User says based on the User and Bot\'s chat history and the information about the topics they are discussing about.Take a look at the example for guidance.\nExample:\nHere is some data on the topics the User and Bot are discussing about:\n"{0}"\nHere is a conversation summary between User and Bot:\n"{1}"\nBased on the chat history and the data on topics that the User and the Bot are chatting about, predict what might have been said following this dialogue by the User.\nUser: "{2}"\nBot: "{3}"\nNow try it yourself.\nHere is some data on the topics the User and Bot are discussing about:\n"{4}"\nHere is a conversation summary between User and Bot.\n"{5}"\nBased on the chat history and the data on topics that the User and the Bot are chatting about, predict what might have been said following this dialogue by the User.\nUser: "{6}"'
knowledge_and_summary_pplbased_flanT5_withex='The task is to give a suitable response to what the User says based on the User and Bot\'s chat history and the information about the topics they are discussing about. Learn from the example first.\nExample:\nHere is some data on the topics the User and Bot are discussing about:\n"{0}"\nHere is a conversation summary between User and Bot:\n"{1}"\nIn the light of the chat history and information about topics that the User and the Bot are chatting on, predict what might have been said following this dialogue by the User.\nUser: "{2}"\nBot: "{3}"\nNow try it yourself.\nHere is some data on the topics the User and Bot are discussing about:\n"{4}"\nHere is a conversation summary between User and Bot.\n"{5}"\nIn the light of the chat history and information about topics that the User and the Bot are chatting on, predict what might have been said following this dialogue by the User.\nUser: "{6}"'

if __name__ == "__main__":
    # Extract the variables above into a pandas dataframe automatically
    import pandas as pd
    df = pd.DataFrame(globals().items(), columns=['variable', 'value'])
    # Remove the variables that are not templates
    df = df[~df['variable'].str.startswith('__')]

    """Add following columns with no values
    --dataset: Dataset to use (MSC or TC)
    --model: Model to use (flan-t5, tk-instruct, T0)
    --prompt_type: "manual" or "ppl"
    --few_shot: Use 1 example per along with each query, otherwise zero_shot
    --background_knowledge: Use background knowledge or not (in summarized format)
    --history_signal_type: Type of history signal (full, peg, bart, recent-k, semantic-k, none)
    --history_k: Number of utterances to use in recent-k or semantic-k
    """

    # Add dataset column
    df['dataset'] = ""
    df['model'] = df['variable'].str.lower().apply(lambda x: "flan-t5" if "flan" in x else "tk-instruct" if "tk" in x else "T0" if "t0" in x else "")
    df['prompt_type'] = df['variable'].apply(lambda x: "ppl" if "ppl" in x else "manual")
    df['few_shot'] = df['variable'].apply(lambda x: "ex" in x)
    df['background_knowledge'] = df['variable'].apply(lambda x: "knowledge" in x or "persona" in x)
    df['history_signal_type'] = ""
    df['history_k'] = ""

    df = df.reindex(columns=['dataset', 'model', 'prompt_type', 'few_shot', 'background_knowledge', 'history_signal_type', 'history_k', 'variable', 'value'])

    df.to_csv('templates.csv', index=False)