cpu:Evaluator.py
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CONDA_PREFIX}/lib/ python3 Evaluator.py --compute cpu

gpu:Evaluator.py
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CONDA_PREFIX}/lib/ python3 Evaluator.py --compute gpu
